### ISSUE TITLE
Suggestion : Mailhog does not support ARM docker images

### ISSUE THREAD

**Issue by bryanrscott** [wodby/docker4laravel#3]
### Issue
Mailhog does not support arm native images.   Suggest adding mailpit docker image, which is a drop in replacement.   https://github.com/axllent/mailpit
  
### Host OS 
macOS Sonoma

### Suggested Solution
Adding in compose.yml

\#  Alternative to mailhog with ARM docker images.
\#  mailpit:
\#    image: axllent/mailpit
\#    container_name: "${PROJECT_NAME}_mailpit"
\#    labels:
\#    - "traefik.http.services.${PROJECT_NAME}_mailpit.loadbalancer.server.port=8025"
\#    - "traefik.http.routers.${PROJECT_NAME}_mailpit.rule=Host(`mailpit.${PROJECT_BASE_URL}`)"

**Comment by csandanov** [comment]
Thank you!
